### ISSUE TITLE
Vult Not Backward Compatible With VCV Rack 0.6.0?

### ISSUE THREAD

**Issue by vogelscheiss** [modlfo/vult#24]
Having an issue. Recently installed VCV Rack 0.6.0. 

- Vult modules came up as missing after installation.
- Downloaded VultModulesFree
- VultModulesFree now shows up as an Author. However,
- Old 0.5.1 projects containing Vult modules can't find them
<img width="384" alt="screen shot 2018-04-09 at 3 26 15 pm" src="https://user-images.githubusercontent.com/38222883/38518488-fe209dfe-3c0a-11e8-9ded-21781dfea665.png">

- Apparently this is because this suite of modules has been given a new name: "VultModulesFree". (Is that the reason?)
- Therefore all my old projects containing Vult modules are now broken, which defeats the whole purpose of being able to save patches, doesn't it?

Can something be done about this?  Thanks.

**Comment by modlfo** [comment]
Hi, this repo is for the Vult compiler. For the modules it's this one https://github.com/modlfo/VultModules

You must have had a very old version of the modules. I announced the change at the beginning of the year. I have split the the modules into two versions, the Premium and the Free. The Premium (which is paid) preserves the old slug `VultModules` the free version changed to `VultModulesFree`. Why? because I gave preference to the paid users so I don't break they patches.

In order to fix the patches you have to open them with a text editor and change the slug `VultModules`  to `VultModulesFree` and the patches should load.

There are not gonna be more changes in the future.

**Comment by vogelscheiss** [comment]
I bought the pay version of the modules – they're well worth it. :)

**Comment by modlfo** [comment]
Thanks @vogelscheiss!
