### ISSUE TITLE
Popping in Bleak

### ISSUE THREAD

**Issue by midiguru23** [modlfo/vult#25]
I'm hearing occasional pops in the output of Bleak 0.6.16. I have confirmed this by looking at the output in Scope. I can see the waveform jumping at the moments when the sound has a pop. If drag-and-drop works, I'll be able to drag the video in here. If it doesn't, email me at midiguru23@sbcglobal.net, and I'll send it to you as an attachment. Thanks for doing the great modules!

Oops. This interface doesn't like a .wmv. I'll try zipping it.
[bleak_pops_movie_zipped.zip](https://github.com/modlfo/vult/files/2528070/bleak_pops_movie_zipped.zip)

--Jim Aikin

**Comment by modlfo** [comment]
Thanks for the report. I'll try to fix it and release an update soon.

**Comment by modlfo** [comment]
The popping has been almost eliminated. It can still occur in the triangle wave in the highest octave  (C7 to C8). In order to remove it completely I have to make the algorithm more complex which will increase the CPU consumption. If you need to use that octave switch instead to Vessek which does not have those problems.

This will be fixed in v0.6.17.
